### ISSUE TITLE
W1/EX2: Some minor markup issues

### ISSUE THREAD

**Issue by KrijnHoetmer** [ChanelZM/browser-technologies#1]
Some notes to keep an eye on:

> `<html lang="en">`

Is this really the language used in your app? :)

> `<img src="./img/fundawonen-logo.svg" alt="Funda logo" />`
> `<img class="pictureofhouse" src="img/fundawonen-logo.svg" alt="Foto van huis" />`

Please read some of the [guidelines on alternative text for images](https://html.spec.whatwg.org/multipage/embedded-content.html#alt). Directly from the HTML specification, so some hard core stuff, but make yourself familiar with this specification (and searching in it), since it's one of the most important specifications in our work field.

Nice markup over all!

**Comment by ChanelZM** [comment]
Ok, I've read the article, but I don't know how to make it better, since its just placeholder text. I'm using transparency to insert houses from the api into html and i'm looping through the houses so the alt text is different for every house.

**Comment by KrijnHoetmer** [comment]
> [...] so the alt text is different for every house

My point exactly, so then perhaps `alt=""` is a better option here.

> `alt="Funda logo, it has a dark brown background with Funda on it and a yellow border"`

That's overdoing it :) See [the section on logos](https://html.spec.whatwg.org/multipage/embedded-content.html#a-short-phrase-or-label-with-an-alternative-graphical-representation:-icons,-logos).
