### ISSUE TITLE
W1/EX2: localStorage

### ISSUE THREAD

**Issue by KrijnHoetmer** [ChanelZM/browser-technologies#6]
> In the funda code I do have a fallback for when localStorage isn't available but experimenting with other options doesn't hurt.

Can't find this fallback (in [script.js](https://github.com/ChanelZM/browser-technologies/blob/master/Week1/funda/docs/js/script.js)), are you using `localStorage` at all?

**Comment by ChanelZM** [comment]
Oh shit, I forgot that I only used localStorage for the final assignment for Webapp from Scratch
